name: build

on:
  push:
    branches:
      - main
      - '3.0'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '*.txt'
  pull_request:
    branches:
      - main
      - '3.0'
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '*.txt'

jobs:
  build:
    strategy:
      matrix:
        #        os: [ ubuntu-latest,macos-latest,windows-latest ]
        os: [ Ubuntu-22.04 ]
        java: [ 8 ]
        maven: [ '3.6.3' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: get TDengine
        run: |
          wget https://github.com/taosdata/TDengine/releases/download/ver-3.3.6.0/TDengine-server-3.3.6.0-Linux-x64.tar.gz

      - name: install
        run: |
          tar -zxf TDengine-server-3.3.6.0-Linux-x64.tar.gz
          cd TDengine-server-3.3.6.0
          sudo ./install.sh -e no

      - name: shell
        run: |
          cat >start.sh<<EOF 
          ulimit -n 65535 && TAOS_SUPPORT_VNODES=256 taosd
          EOF

      - name: taosd
        run: nohup sudo sh ./start.sh &

      - name: start taosadapter
        run: sudo taosadapter &

      - name: checkout
        uses: actions/checkout@v4
        with:
          path: 'jdbc-workspace'

      - name: set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Test
        working-directory: jdbc-workspace
        env:
          TDENGINE_CLOUD_URL: ${{ secrets.TDENGINE_CLOUD_URL }}
        run: mvn -B clean verify --file pom.xml



